pixel: Move qti_kernel_headers out of namespace
QTI modules depend on qti_kernel_headers. Even though
they are not used on Tensor Pixels, because they
are hidden behind a namespace, if we namespace a HAL
such as IPA, it breaks compile with the errors below.

Fixes
error: vendor/qcom/opensource/data-ipa-cfg-mgr-legacy/ipanat/Android.bp:3:1: "libipanat" depends on undefined module "qti_kernel_headers"
Module "libipanat" is defined in namespace "vendor/qcom/opensource/data-ipa-cfg-mgr-legacy" which can read these 2 namespaces: ["vendor/qcom/opensource/data-ipa-cfg-mgr-legacy" "."]
Module "qti_kernel_headers" can be found in these namespaces: ["hardware/google/pixel"]
error: vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/Android.bp:3:1: "libipanat" depends on undefined module "qti_kernel_headers"
Module "libipanat" is defined in namespace "vendor/qcom/opensource/data-ipa-cfg-mgr" which can read these 2 namespaces: ["vendor/qcom/opensource/data-ipa-cfg-mgr" "."]
Module "qti_kernel_headers" can be found in these namespaces: ["hardware/google/pixel"]

Change-Id: I27b7d9089070044e230f232b374d68d22ad0020f